### ISSUE TITLE
Made defaults vimrc-overrideable

### ISSUE THREAD

**Issue by dbarnett** [noahfrederick/vim-neovim-defaults#1]
Since plugin/neovim_defaults.vim is sourced _after_ evaluating the .vimrc, any settings there take precedence over inline configuration in your vimrc. For example, if you have `set noincsearch` in your vimrc, it will always be overridden by the `set incsearch` in plugin/neovim_defaults.vim. To override those settings a user would have to define an after/plugin/ file to be evaluated even later in startup.

Since the purpose is to provide default settings and overriding some will be the common case, it would be good to make it more straightforward and get rid of the gotcha somehow. An inclusion guard like

``` vim
if exists('s:loaded')
  finish
endif
let s:loaded = 1
```

would at least give users the option to source the file immediately after installing the plugin and before overriding any settings and not have them overridden later.

**Comment by noahfrederick** [comment]
Yes indeed. Thanks!
