### ISSUE TITLE
Implement new defaults for filetype, syntax

### ISSUE THREAD

**Issue by ghost** [noahfrederick/vim-neovim-defaults#2]
https://github.com/neovim/neovim/pull/4252/files

I'm not sure if this default would be problematic in a plugin though. Feel free to close if it is.

**Comment by noahfrederick** [comment]
I'm a little wary of the change for a few reasons:
- Will there be any adverse effects if these settings are set late (i.e., when regular plugins are loaded)?
- How do we respect preferences already set in the vimrc?
- Is it useful? This is a plugin, and plugin managers tend to enable these things themselves. No guarantee a plugin manager is in play, though. (This is probably not a valid concern.)

These are questions I haven't gotten around to answering yet.

**Comment by ghost** [comment]
that's exactly why I didn't submit a PR to add it. I'm not enough of a vim expert to know.

**Comment by ghost** [comment]
Your readme reminded me of sensible.vim: Take a look at the code here: https://github.com/tpope/vim-sensible/blob/master/plugin/sensible.vim#L11

Has anybody had any problems with sensible.vim doing this?

**Comment by noahfrederick** [comment]
Okay, I gave it more thought, and decided to enable file-type plug-ins/syntax unconditionally per sensible.vim. If anyone finds this to be a problem, please propose an alternative.
